### ISSUE TITLE
Not able to access individuals in DEA

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1104] opened 2023-12-14 09:49 UTC
https://avni.freshdesk.com/a/tickets/3324 - root cause seems to be same as this: https://github.com/avniproject/avni-product/issues/1446 Just make sure and if that is the case - merge the tickets if it is from the same org.

**Comment by 1t5j0y** [comment] 2023-12-14 11:38
Confirmed root cause is same as avniproject/avni-product#1446

@mahalakshme Also, this is now fixed with the server fix deployed. We can close this freshdesk ticket instead of merging.

**Closed by 1t5j0y** 2023-12-14 11:38 UTC

**Comment by mahalakshme** [comment] 2023-12-14 11:54
@1t5j0y but they will still face the issue when they open an individual for which data is missing right? So thought until we recover the data if the rootcause is same, the issue will not be resolved.

**Comment by 1t5j0y** [comment] 2023-12-14 11:58
@mahalakshme Loading an individual does not throw an error any more. For individuals with / without missing data.
