### ISSUE TITLE
Need a mechanism to bulk assign users to user groups

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#825] opened 2022-10-12 04:14 UTC

**Comment by vinayvenu** [comment] 2022-10-13 04:26
Closing as duplicate of https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/782

**Closed by vinayvenu** 2022-10-13 04:26 UTC
Labels: enhancement
