### ISSUE TITLE
Fix updating a location's parent via UI

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-webapp#1217] opened 2024-05-08 11:53 UTC
### Need:
Currently when a parent of a location is updated via UI it is not handled correctly. The subjects of the updated locations are not marked for migration and hence could lead to association error. Could be one of the reasons why some association errors for which root cause could not be determined has happened.

### Technical analysis:
- Marking all the subjects for migration might not be a scalable solution. As an alternative, we can find out the users for which reset sync can be done, based on the location hierarchy change. This can be done using ```virtual_catchment_address_mapping_table``` or ```catchment_address_mapping```. On some analysis [here](https://gist.github.com/vinayvenu/5f6d4ebee83ef5bfdda0b61d9900ac39), catchment_address_mapping seems to be faster. The decision is upto the developer.
- Also to maintain uniformity of code, refer ```ResetSyncService.java -> recordCatchmentChange() in avni_server```

### AC:
Identify the users to be marked for complete reset sync using the below strategy: Say, A's parent is updated to B from C

if any of A or A's children have subjects registered in it then,
    - check for users with catchments which have any of (B's location, any of the B's parents' locations, C, any of C's parent locations) 
    - mark the users for complete reset sync
else if neither of A or A's children have subjects registered then,
    - no need to mark any of the users for reset sync

### Out of scope:
Identifying more smart strategies to minimise the impact of reset sync.

## Old: ignore
-----------------------
### Need:
We 've not handled updating of location parent correctly. The subjects of the updated locations are not marked for migration and hence could lead to association error. Could be one of the reasons why some association errors for which root cause could not be determined has happened. This can be achieved by creating the locations in destination + deleting of the old locations. So no need to support this, since technically supporting this as well is not easy.

### AC:
Disable updating location's parent for already created locations.
- Like shown in the below screenshot, disable updating parent similar to type.
<img width="1504" alt="Screenshot 2024-05-20 at 4 17 51 PM" src="https://github.com/avniproject/avni-webapp/assets/10369963/0a7cd020-b240-439b-9076-02e79f9648b4">

### Steps to reproduce:
env: staging org: RWB_Niti 
current status of locations: Akola is under Maharashtra, and it contains Patur Taluka

- Go to Admin -> Upload
- Upload this file to change the parent of Akola to dummy1
[edit_location_edit_rwb_2.csv](https://github.com/avniproject/avni-webapp/files/15248465/edit_location_edit_rwb_2.csv)
- Akola's parent gets updated, but lineage of Patur still says its State is Maharashtra

### AC:
- Do not allow parent of a location to get updated. Just update the same parent as parent of the location, not the the new one mentioned in the CSV
- No need to handle/show error since this is not a common case. It is just that we should not allow to avoid corrupted data.

### Suggestions:
- so far needed for 2 cases: RWB(had children) and LFE(no children)
- for no children/with children they need to move all the children to new location - if we remove this - then manual need to delete and create the location tree, updating of lineages need to handle
- With children - also need to do updating last_modfied_date_time or inserting sub., migrations needed 
- So - we shud know and not reply on user reporting the error message to us - LocationMigration? if the migrated child or its children has subjects registered.

### Inputs:
- Introduce location migration
- Wire this with API 
- Major change request 
- reset sync of all catchments where locations are associated with

### Code reference:
https://github.com/avniproject/avni-server/blob/290e434960dd0e89a80f9d13859d1efdc0219ff8/avni-server-api/src/main/java/org/avni/server/importer/batch/csv/writer/LocationWriter.java#L151

### Reference source card: 
https://app.zenhub.com/workspaces/avni-product-deprecated-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/380

### Analysis notes:
Not allowed because then need to update the lineage of all parents and then need to do reset sync for subjects of source and destination addresses. So as an alternative, new location can be created in the destination and /subjectMigrationBulk can be called via API or via code if we are gonna support. We can update the location parent from UI as well. Here as well we have not handled migration of subjects but we have done `updateDescendantLocationLineage`. So the question is should we support? We might get association errors if not handled.

**Comment by petmongrels** [comment] 2024-06-05 10:07
Lets add integration test for this with valid scenarios.

**Comment by AchalaBelokar** [comment] 2024-07-02 09:37
- [ ] I tried to change this location with dummy1, Maharashtra with this csv 

[edit_location_edit_rwb_2.csv](https://github.com/user-attachments/files/16065716/edit_location_edit_rwb_2.csv)

got this error 

[errors-edit_location_edit_rwb_2 (1).csv](https://github.com/user-attachments/files/16065717/errors-edit_location_edit_rwb_2.1.csv)

- [ ] I tried with whole location change with lowest level still I got same error
-

**Comment by AchalaBelokar** [comment] 2024-07-03 02:37
- [ ] I login in to the AchalaB@rwbniti after that I chenge the state name of maharashtra which contain the akola district I change the state of akola district dummy1 .. and I login to client with AchalaB@rwbniti it is successfully login but after login I try to click on farmer it is showing this parent are mandatory for LocationMapping, Keys being saved - uuid,parent,child,voided. UUID: 85c1d940-c8cf-42f6-8af5-eead9765769f
at create (address at index.android.bundle:1:1095483)
at anonymous (address at index.android.bundle:1:1247189)
at anonymous (address at index.android.bundle:1:1247102)
at map ((native)::)
at anonymous (address at index.android.bundle:1:1247088)
at write ((native)::)
at write (address at index.android.bundle:1:1095928)
at bulkSaveOrUpdate (address at index.android.bundle:1:1247060)
at persistAll (address at index.android.bundle:1:1582768)
at processResponse (address at index.android.bundle:1:1585937)
at anonymous (address at index.android.bundle:1:1586196)
at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
at apply ((native)::)
at anonymous (address at index.android.bundle:1:247081)
at _callTimer (address at index.android.bundle:1:246075)
at _callReactNativeMicrotasksPass (address at index.android.bundle:1:246240)
at callReactNativeMicrotasks (address at index.android.bundle:1:248162)
at __callReactNativeMicrotasks (address at index.android.bundle:1:98201)
at anonymous (address at index.android.bundle:1:97340)
at __guard (address at index.android.bundle:1:98078)
at flushedQueue (address at index.android.bundle:1:97251)
at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:97194)

**Comment by 1t5j0y** [comment] 2024-07-04 06:36
Tried creating a minimal reproducible example but did not hit the above error after changing parent multiple times.

Scenario constructed: 
User1 with Catchment1
User2 With Catchment2
Catchment1 with locations Country1
Catchment2 with locations Country2
Country1 hierarchy -> Country1, State1, District1, Village1
Country2 hierarchy -> Country2, State2, District2, Village2

Registered subjects in both Village1 and Village2.

Changed parent of State1 and State2 multiple times across Country1 and Country2 and verified reset sync was displayed and no error during sync for both users.

Moving this back to QA ready since sync behaviour was not changed as part of this card and unable to reproduce this error.

**Closed** 2024-07-10 10:14 UTC
