### ISSUE TITLE
Issues with bundle import of dashboards

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-webapp#1265] opened 2024-06-24 10:51 UTC
Description : 

The offline dashboard fails to remove the voided while performing a bundle upload. Additionally, the filters are not updated or added according to the new data in the uploaded bundle. Eg : if the Dashboard has the section A and B and B is voided or remove from the dashboard and we upload the bundle in the prod which as section B already present it is not voiding the section.

env : prod
org : apfodisha
user : dineshg@apfodisha

steps to reproduce : 

1.Login to the uat app (apfodishauat)
2.download the bundle with the latest update.
3.login to prod (apfodisha)
4.upload the bundle 

Expected result : As per the UAT data the prod should be updated - both filters and section deletion
Actual result : Offline dashboard card or sections and custome filter  are not updated properly.

Doc : (UAT Bundle)
[APF Odisha UAT (1).zip](https://github.com/user-attachments/files/15954039/APF.Odisha.UAT.1.zip)

Prod : bundle before upload 

[APF Odisha.zip](https://github.com/user-attachments/files/15954052/APF.Odisha.zip)

**Comment by 1t5j0y** [comment] 2024-06-26 05:40
Treat this as a dupe of avniproject/avni-webapp#1231 which has already been fixed and slotted for 10.0 @mahalakshme ? Significant refactoring of the affected area has been done in that card.

**Comment by mahalakshme** [comment] 2024-06-26 05:45
@1t5j0y sure are the above issues also already fixed in 10.0?

**Comment by 1t5j0y** [comment] 2024-06-26 05:46
We will know when the card is QAd.

**Closed** 2024-10-10 22:13 UTC
