### ISSUE TITLE
Home button is broken

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-webapp#913] opened 2023-03-01 11:05 UTC
Clicking on the home button is error prone. 

To Reproduce
- Login
- Go to Admin
- Click on Home button

It should take you to the home screen. Right now, it stays on the same screen

**Comment by petmongrels** [comment] 2023-03-02 11:11
cannot reproduce now in production

**Comment by 1t5j0y** [comment] 2023-03-03 05:04
this is a staging only issue as of now.. probably introduced in another ticket part of this release - https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/901

**Comment by petmongrels** [comment] 2023-03-03 10:38
we have lot of magic/logic in our code related to navigation in web app related to home page, default page, roles, etc. Ideally the logic should be centralised in once place. It is all over the code. I would suggest that given that the current issue number: 913 is only happening for super admin - we don't do it as a bug and instead convert into a story and prioritise.

**Comment by 1t5j0y** [comment] 2023-03-07 06:55
Putting in a fix for this issue with the magic as-is as discussed on standup so as not to affect productivity. Separate issue to be raised to clean up the magic.

**Comment by vinayvenu** [comment] 2023-03-10 04:41
Added card https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/922 as followup.

**Comment by vinayvenu** [comment] 2023-03-10 05:42
Home button from Documentation, Assignment, Broadcast, Translations, Reports, Support and Training and Canned Reports take you to Admin page.

**Closed** 2023-04-12 14:20 UTC
Labels: bug
