### ISSUE TITLE
Need a mechanism to assign user identifier while creating users

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#824] opened 2022-10-12 04:10 UTC
Requirement/Need -

In recent implementation APF, there are large number of users being created for 5 different organisations/NGOs , each time assigning identifier is not an easy task as the dropdown list is too long and also remembering the last set of identifier assigned becomes difficult.

**Comment by vinayvenu** [comment] 2022-10-13 04:28
Closed as a duplicate of https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/avni-webapp/782

**Closed by vinayvenu** 2022-10-13 04:28 UTC
Labels: enhancement
