### ISSUE TITLE
Custom Dashboard Filters Creation not Supported During Bundle Upload.

### ISSUE THREAD

**Issue by adamsanadi6** [avniproject/avni-webapp#1107] opened 2023-12-21 07:28 UTC
**Describe the bug**
Created dashboard filters in UAT, but after doing the bundle upload to production, the dashboard filters are not getting created as part of the bundle upload.

**To Reproduce**

1. Go to any org which has dashboard filters(mobile creche trial) or create the dashboard filters.
2. Take the bundle and do the upload.
3. Go to the offline dashboard and check for filter.

**Expected behavior**
Filters should also be updated or created as part of the bundle upload.

**Test Data**
Give details of example users, environment detail, username against which this issue is happening.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by mahalakshme** [comment] 2024-01-29 05:28
@adamsanadi6 is this issue duplicate of this: https://github.com/avniproject/avni-webapp/issues/1027 ?

**Comment by adamsanadi6** [comment] 2024-01-30 04:53
@mahalakshme , both issues are entirely different, but they are both related to the custom dashboard. This one with respect to the dashboard filters – they are not being created during bundle upload. Meanwhile, in issue #1027 , we are experiencing the duplication of dashboards (void check is missing) after voiding the dashboard section to ReportCard mapping.

**Comment by mahalakshme** [comment] 2024-02-09 13:33
added to https://github.com/avniproject/avni-server/issues/559 hence closing this.

**Closed by mahalakshme** 2024-02-09 13:33 UTC
