### ISSUE TITLE
Issue with location upload having same name but different hierarchy

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#515] opened 2020-11-17 11:57 UTC
**Describe the bug**
For example, in one of the implementations (CES), having two different hierarchies>
1. State >> District
2. City >> Division >> Area

When the locations for the first hierarchy is uploaded, it created Delhi as state and when the second hierarchy was uploaded having Delhi as city, the locations got uploaded under Delhi State and it dint create City for it.  

Both the hierarchies are supposed to be used at different places so we need to have state and city both.

**To Reproduce**

**Expected behavior**

**Test Data**
Give details of example users, environment detail, username against which this issue is happening.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**(Developer fixing the bug should fill this checklist)
- Does the fix require extensive regression testing?
  - [ ] Yes
  - [ ] No
- Are you mentioning the required scenarios that could be affected?
  - [ ] Yes
  - [ ] No

**Comment by arjunk** [comment] 2021-06-15 11:00
Duplicate of https://github.com/avniproject/avni-webapp/issues/595

**Closed by arjunk** 2021-06-15 11:00 UTC
Labels: bug
