### ISSUE TITLE
[Admin] Ability to enable/disable auto sync

### ISSUE THREAD

**Issue by arjunk** [avniproject/avni-webapp#620] opened 2021-06-22 10:56 UTC
### Motivation
Many times for testing we need to connect  to prod organisations. Now that we have auto sync feature, this holds the risk of by mistake pushing test data to server.

### Acceptance Criteria
1. As an org admin i should be able to enable/disable  auto sync for a user in my organisation.

### Test Scenarios

- [ ] Including all required translations

**Comment by himeshr** [comment] 2023-08-01 06:04
Duplicate of avniproject/avni-client#966

**Comment by himeshr** [comment] 2023-08-01 06:05
Duplicate of https://github.com/avniproject/avni-client/issues/966

**Closed by himeshr** 2023-08-01 06:05 UTC
