### ISSUE TITLE
Server communication error is showing after clicking user on Identifier User Assignment screen

### ISSUE THREAD

**Issue by AchalaBelokar** [avniproject/avni-webapp#1029] opened 2023-08-22 09:40 UTC
**Describe the bug**
Server communication error is showing after clicking user on Identifier User Assignment screen

![Screenshot 2023-08-22 at 2 57 45 PM](https://github.com/avniproject/avni-webapp/assets/104890488/e2efbcf3-2b80-4ed8-b5ad-28aef334867a)
this is happen with super and org admin

**To Reproduce**
search one org which is having the identifier source 
1. Go to admin
2. Click on Identifier user assignment 
3. click on any user

**Expected behavior**
error msg should not come.

**Screenshots**

https://github.com/avniproject/avni-webapp/assets/104890488/2cd9caf3-b7bb-4a03-8882-dd55f560b365

**Comment by 1t5j0y** [comment] 2023-08-31 09:49
appears to have been already fixed by @petmongrels based on chat. Moving to ready for qa.

**Comment by AchalaBelokar** [comment] 2023-09-07 04:35
<img width="1308" alt="Screenshot 2023-09-07 at 10 04 32 AM" src="https://github.com/avniproject/avni-webapp/assets/104890488/e4c1bcd0-1c44-4ea0-a1e1-1cc07da86148">
getting this error

**Comment by 1t5j0y** [comment] 2023-09-07 04:41
@AchalaBelokar that error message is related to functionality introduced in https://github.com/avniproject/avni-webapp/issues/1022 and looks like expected behaviour. Please try with non overlapping identifiers.
This card should not be QA failed due to this error unless you are still seeing communication error.

**Comment by ashusvnath** [comment] 2023-09-15 10:10
QA Observation:

No error occurs on clicking any Identifier User Assignment.

**Closed by ashusvnath** 2023-09-15 10:10 UTC
Labels: bug
